apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-v4yhbq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v4yhbq
  namespace: my-nginx-v4yhbq
  labels:
    name: nginx-v4yhbq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-v4yhbq
  template:
    metadata:
      namespace: my-nginx-v4yhbq
      labels:
        name: nginx-v4yhbq
    spec:
      containers:
      - name: nginx-v4yhbq
        image: nginx
        ports:
        - containerPort: 80

